name: "Repository Mirror"

on:
  - push

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Mirror"
    steps:
      - uses: pkgstore/github-action-mirror@main
        with:
          source_repo: "https://github.com/Gyarbij/Artemis.git"
          source_user: "${{ secrets.MIRROR_SOURCE_USER_GITHUB }}"
          source_token: "${{ secrets.MIRROR_SOURCE_TOKEN_GITHUB }}"
          target_repo: "https://cgcsu@dev.azure.com/cgcsu/Prodigy/_git/Artemis.git"
          target_user: "${{ secrets.MIRROR_TARGET_USER_DEVOPS }}"
          target_token: "${{ secrets.MIRROR_TARGET_TOKEN_DEVOPS }}"
